remote_theme: daviddarnes/alembic

exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site Settings
title: Immersive Media Pocket Reference
description: A resource for XR design.

# Header Nav
navigation_header:
- title: Home
  url: /
- title: Glossary
  url: /glossary/
- title: Resources
url: /resources/
- title: Notes
  url: /notes/
- title: Guides
  url: /Guides/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"